### ISSUE TITLE
Including self main.scss in exceptions does not excludes it.

### ISSUE THREAD

**Issue by gangsthub** [mikevercoelen/gulp-sass-glob#37]
I have:

```
app
  `--/scss
    `--/main.scss
  `--/component
    `--/_file.scss
  `--/ignore
  gulpfile.js
```

and I'm trying to do:

```
sassGlob({
            ignorePaths: [
                'app/ignore',
                'app/scss/*.scss' // this aint working.
            ]
        }
```

and including *everything* out of my scss folder like this in my `main.scss`:
```
@import '../**/*.scss';
```

It results in a regular sass error `@import loop has been found`; I assume *as a sass error*, not sassGlob. (It's importing itself `>> @import "main.scss";`)

But could this be targeted here? Thanks.

BTW, amazing plugin! Thanks!

**Comment by tomgrooffer** [comment]
@gangsthub Hi thanks for asking a question and so making the plugin better.

I have looked into it and you are totally right, this is not the expected behavior.

I'm going to dive into the code asap. For now I hope you came up with a temporary solution. I keep you posted.

Thanks

**Comment by gangsthub** [comment]
Sorry for the typos, and thanks to you, Mike

**Comment by webegguk** [comment]
ignorePaths would be really helpful for a project I'm developing that requires different sets of css for different sites which all share the same library of sass. This doesn't work for me either so a big +1 from me on this. Again, great plugin other than this.

**Comment by mikevercoelen** [comment]
@webegguk @gangsthub Could you take a look at the code and see if you guys can help me with creating a PR for this feature?

Is it still relevant? Give me a bump so I can take a look at it ;)

**Comment by paymok** [comment]
@mikevercoelen  I also come across with this problem and try to dig into the code, the issue is seems related to minimatch library you are using. 

For example, if I am compiling the sass in a windows environment, 

main.scss
`@import "../../folder/app/**/*.scss";`

pipe 
`return gulp.src('./theme/sass/**/*.{scss,sass}')
    // Initializes sourcemaps
        .pipe($.sourcemaps.init())
        .pipe($.sassGlob({
            ignorePaths: [
                '**/plugins/**/*.scss'
            ]
        }))`

This will not work because in inside the path matching logic 
`files.forEach(function (filename) {
          if (filename !== file.path && isSassOrScss(filename)) {
            // remove parent base path
            filename = _path2.default.normalize(filename).replace(basePath, '');
            if (!ignorePaths.some(function (ignorePath) {
              return (0, _minimatch2.default)(filename, ignorePath);
            })) {
              // remove parent base path
              imports.push('@import "' + (0, _slash2.default)(filename) + '"' + (isSass ? '' : ';'));
            }
          }
        });`

`console.log(filename); // C:\myWorkplace\projectFolder\web\folder\app\plugins\pluginA\style.scss
console.log(ignorePath); // **/plugins/**/*.scss 
(0, _minimatch2.default)(filename, ignorePath);  // false `

But if I change the ignorePath to become  **'**\\plugins-agd\\**\\*.scss'** in the pipe.
`console.log(filename); // C:\myWorkplace\projectFolder\web\folder\app\plugins\pluginA\style.scss
console.log(ignorePath); // **\plugins\**\*.scss 
(0, _minimatch2.default)(filename, ignorePath);  // true `

I suggest should try to get the path according to linux base style, regardless of what OS we are using. 
Alternatively, let say I use Windows for development but Ubuntu for the build, in this case i will just append both style to the ignorePaths array. 

`return gulp.src('./theme/sass/**/*.{scss,sass}')
    // Initializes sourcemaps
        .pipe($.sourcemaps.init())
        .pipe($.sassGlob({
            ignorePaths: [
                '**/plugins/**/*.scss',
                '**\\plugins\\**\\*.scss'
            ]
        }))`

**Comment by gangsthub** [comment]
Great point, @paymok! Thank you.

This reminded me to a @sindresorhus' package called **slash**:
https://github.com/sindresorhus/slash

I would recommend using it or a simmilar one to get the system's slash style.

Also, the article cited it's pretty interesting:
http://superuser.com/a/176395/6877

According to it, as cited from slash readme:
> Forward-slash paths can be used in Windows as long as they're not extended-length paths and don't contain any non-ascii characters.

Hope it adds also some light.

Kind regards, Mike
